### ISSUE TITLE
Issue with BingMapsRESTToolkit.Response

### ISSUE THREAD

**Issue by dhna88** [microsoft/BingMapsRESTToolkit#29]
I am trying to run the samples of the RESTToolkitTestApp that i have downloaded from this repositery. When I click on Route, Transit Route or any other, I get the following error: ''There was an error deserliaizing the object of type BingMapsRESTToolkit.Response. Encountered un expected charecter '<' ''. I have just added the key and didnt touch anything else in the code, just downloaded it and then executing it under Visual Studio Community version 2017. I couldnt see from where it comes in the code

**Comment by rbrundritt** [comment]
This error indicates that XML/HTML was returned by the response. I believe the REST services do this when they hit an error on the server, usually due to a bad request. Try watching the network traffic (fiddler works well) and inspecting the URL being used in the request and verify it is correctly formatted.

**Comment by IoTGirl** [comment]
Closing as Answered & Stale
