### ISSUE TITLE
DistanceMatrixRequest throws an exception "Encountered unexpected character"

### ISSUE THREAD

**Issue by 27maxou27** [microsoft/BingMapsRESTToolkit#56]
I am trying to perform a distance matrix request between two simple waypoints:

![Screeenshot](https://user-images.githubusercontent.com/34162164/131313356-6954f1b2-fcc5-4629-b21d-6e73d19bedb8.png)

I get the following exception from BingMapsRESTToolkit during execution:

"There was an issue downloading and serializing the results. Results Download URL: https://routematrixpremium.blob.core.windows.net/finalresults/7ac8bb8f-4ebe-48bf-9b8b-da5c7a73abd2
There was an error deserializing the object of type BingMapsRESTToolkit.DistanceMatrix. Encountered unexpected character 'ï'."

Here is the response when following the link provided by the exception message:

![Screenshot 2021-08-30 at 10-47-08 https routematrixpremium blob core windows net](https://user-images.githubusercontent.com/34162164/131312824-7da53a0d-45d1-409d-853f-86a8459daee3.png)

I am kind of clueless because there is no sign of a "ï" in the response and no string parameters. The origins and destinations both contains a single SimpleWaypoint with valid Latitude/Longitude pairs (visible in the response screenshot). I am using the latest version of the toolkit (v1.1.4) in a .NET 5 project with an Entreprise Bing Maps account.

I haven't been able to make the DistanceMatrixRequest.Execute() work after many tries. It is always about the same character "ï".

**Comment by 27maxou27** [comment]
After further testing, the problem seem to arise only when specifying the parameter "StartTime". When set to null, there is no more deserialization problem.

**Comment by rbrundritt** [comment]
I was able to reproduce this issue. Digging into this I found that an async request is made instead of a sync request and the final result response from the async API ends up being slightly different from the sync result. The main difference is that the namespace type is not specified, and this ends up breaking the data contracts. I know for certain this code worked when it was originally written years ago, so not sure when the API changed.

In any case, I have made an update to this library to handle this case. This update is in version 1.1.5 of this library which is currently only available as code (no NuGet package update, not sure who does that these days for this project). But you can load the BingMapsRestToolkit project by downloading the source code and copying the contents of the `Source` folder into your solution folder. Then in your solution add an "Existing project" and select the "BingMapsRESTToolkit.csproj" file.
