### ISSUE TITLE
Bing Maps Autosuggest API

### ISSUE THREAD

**Issue by smarteez17** [microsoft/BingMapsRESTToolkit#61]
Hi Can I used your toolkit to get values from Autosuggest API? can you provide an example . i want to do something like this but cant find the method 

var request = new GeocodeRequest()
{
    Query = "1 Microsoft way, Redmond, WA",
    MaxResults = 1,	//Only requesting one result in this case as I just want the first result. No need for more, keep the response size small.
    BingMapsKey = BING_MAPS_KEY
};

//Process the request by using the ServiceManager.
var response = await request.Execute();

**Comment by smarteez17** [comment]
Hi @rbrundritt thank you for your repose 

Would it be possiable to contact the deloveper and request that the NuGet package to be updated so myself and other/ futher user can use this NuGet package

**Comment by rbrundritt** [comment]
I'm not sure about that. I created this project a little over 6 years ago, and then handed it off when I left Bing Maps 5 years ago. The team that picked it up looks to have made one release since then. Looking around, the people who initially took this over seem to have moved on to other things, so not sure who, if anyone, is maintaining this any longer. Note that [Azure Maps](https://docs.microsoft.com/en-us/azure/azure-maps/), was released around the same time as the last update of this NuGet package (that platform has 22 different search APIs, all with more cross API alignment).
