### ISSUE TITLE
GeocodeRequest - Address mapping

### ISSUE THREAD

**Issue by smarteez17** [microsoft/BingMapsRESTToolkit#62]
the GeocodeRequest call is not mapping all fields for Address I been testing and CountryRegionIso2, neighborhood and landmark  is always null or blank

**Comment by rbrundritt** [comment]
That is by design as the geocode API doesn't support those values as you can see in the [docs here](https://docs.microsoft.com/en-us/bingmaps/rest-services/locations/find-a-location-by-address). Note that the GeocodeRequest class takes in a `SimpleAddress` object: https://github.com/microsoft/BingMapsRESTToolkit/blob/master/Source/Models/SimpleAddress.cs

Note, if you want to geocode any address returned by another service in Bing Maps, use the `formattedAddress` value of the address with the ["Location by query" API](https://docs.microsoft.com/en-us/bingmaps/rest-services/locations/find-a-location-by-query), for some reason this generally works better on average.
